# port server
server:
  port: 5005
  servlet:
    context-path: /admin

spring:
  application:
    name: tranngocanh
  # MySQL database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/identity_tranngocanh?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



